name: ongkir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0-235.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dropdown_search: 5.0.6
  dio: 5.2.1+1
  http: 1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

